default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: base_rails_project_development

test:
  <<: *default
  database: base_rails_project_test

production:
  <<: *default
  database: base_rails_project_production
  username: base_rails_project
  password: <%= ENV['BASE_RAILS_PROJECT_DATABASE_PASSWORD'] %>
